# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 074c2f26f9978e4e77f75a6fa162ec2ce3a37b76f0a4c22ba7d051be23fe54f51b2e0533cc482d916e4f15744f960c20c1a4a557a05cd7726899de58632da8cb

test:
  secret_key_base: f9a52a5a5ecf242d3a854f26c0d2407a35eadd03609c2d96239e8770c59ffd29ae5d3eeb62bd1322ef731bfa8d74864c228b41b83e98d04d8975c93e6d4f3ed3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
